[workspace]
resolver = "2"
members = [
    # Core RET crates
    "crates/radix-engine-toolkit",
    "crates/radix-engine-toolkit-json",
    "crates/radix-engine-toolkit-uniffi",
    # Auxiliary Crates
    "crates/sbor-json",
    # Bindings Crates
    "crates/generator",
    "crates/uniffi-bindgen"
]

# Shared dependencies that all of the crates need - for now this is just the 
# `radixdlt-scrypto` dependencies
[workspace.dependencies]
sbor = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "b82a7db0a0b2da62ea22a640143cd0caf73b6603", features = ["serde"] }
scrypto = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "b82a7db0a0b2da62ea22a640143cd0caf73b6603", features = ["serde"] }
scrypto-test = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "b82a7db0a0b2da62ea22a640143cd0caf73b6603" }
radix-common = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "b82a7db0a0b2da62ea22a640143cd0caf73b6603", features = ["serde"] }
radix-engine = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "b82a7db0a0b2da62ea22a640143cd0caf73b6603" }
radix-engine-interface = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "b82a7db0a0b2da62ea22a640143cd0caf73b6603" }
radix-substate-store-queries = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "b82a7db0a0b2da62ea22a640143cd0caf73b6603" }
radix-substate-store-impls = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "b82a7db0a0b2da62ea22a640143cd0caf73b6603" }
radix-substate-store-interface = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "b82a7db0a0b2da62ea22a640143cd0caf73b6603" }
radix-transactions = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "b82a7db0a0b2da62ea22a640143cd0caf73b6603" }
radix-transaction-scenarios = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "b82a7db0a0b2da62ea22a640143cd0caf73b6603" }

[profile.release]
incremental = false
panic = 'unwind'
codegen-units = 1