[package]
name = "transaction-library"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = { version = "0.4.3", features = ["serde"] }
bech32 = { version = "0.9.0", default-features = false }

serde = { version = "1.0.144", features = ["serde_derive"] }
serde_json = { version = "1.0.85" }
serde_with = { version = "2.0.0", features = ["hex"] }

sbor = { git = "https://github.com/radixdlt/radixdlt-scrypto", branch = "temp/public-tx-validation-functions" }
scrypto = { git = "https://github.com/radixdlt/radixdlt-scrypto", branch = "temp/public-tx-validation-functions" }
transaction = { git = "https://github.com/radixdlt/radixdlt-scrypto", branch = "temp/public-tx-validation-functions" }

[profile.release]
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'
strip = "debuginfo"

[lib]
crate-type = ["cdylib", "lib"]
