[workspace]
resolver = "2"
members = [
    # Core RET crates
    "crates/radix-engine-toolkit",
    "crates/radix-engine-toolkit-json",
    "crates/radix-engine-toolkit-uniffi",
    # Auxiliary Crates
    "crates/sbor-json",
    # Bindings Crates
    "crates/generator",
    "crates/uniffi-bindgen"
]

# Shared dependencies that all of the crates need - for now this is just the 
# `radixdlt-scrypto` dependencies
[workspace.dependencies]
sbor = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "v1.1.2", features = ["serde"] }
scrypto = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "v1.1.2", features = ["serde"] }
scrypto-unit = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "v1.1.2" }
transaction = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "v1.1.2" }
transaction-scenarios = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "v1.1.2" }
radix-engine = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "v1.1.2" }
radix-engine-stores = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "v1.1.2" }
radix-engine-common = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "v1.1.2", features = ["serde"] }
radix-engine-queries = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "v1.1.2" }
radix-engine-interface = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "v1.1.2" }
radix-engine-store-interface = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "v1.1.2" }

[profile.release]
incremental = false
panic = 'unwind'
codegen-units = 1