[package]
name = "radix-engine-toolkit"
version = "0.9.0"
edition = "2021"
build = "build.rs"

[dependencies]
# Crates for Serde serialization.
serde = { version = "1.0.152" }
serde_with = { version = "2.2.0", features = ["hex"] }

# A library which allows us to generate a JSON schema from Rust models
schemars = { version = "0.8.11", features = ["preserve_order"] }

# An attribute macro to setup a model to be serializable and also to have a JSON schema. 
toolkit-derive = { path = "../toolkit-derive" }

# Scrypto dependencies required for the core-toolkit
sbor = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "develop-624a696d" }
scrypto = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "develop-624a696d" }
scrypto_utils = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "develop-624a696d", package = "utils" }
native_transaction = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "develop-624a696d", package = "transaction" }
radix-engine = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "develop-624a696d", optional = true }
radix-engine-common = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "develop-624a696d" }
radix-engine-constants = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "develop-624a696d" }

# Hex is used for the internal hex encoding and decoding of values - serde_with::Hex is used for the
# hex representation during serialization.
hex = { version = "0.4.3", default-features = false }

# Bech32 is used for the network aware addresses (some additional functionality is required which we
# don't expose through the Scrypto Bech32 encoder and decoder)
bech32 = { version = "0.9.0", default-features = false }

# Used for more powerful declarative macros
paste = { version = "1.0.11" }
serde_json = "1.0.91"
regex = "1.7.3"

[dev-dependencies]
scrypto-unit = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "develop-624a696d" }
lazy_static = { version = "1.4.0" }
serde_json = { version = "1.0.91" }

[features]
default = ["radix-engine"]
radix-engine = ["dep:radix-engine"]
