[package]
name = "serializable"
version = "0.8.0"
edition = "2021"

[dependencies]
proc-macro2 = { version = "1.0.49" }
quote = { version = "1.0.23" }
syn = { version = "1.0.107" }

[lib]
proc-macro = true
