[package]
name = "uniffi-bindgen"
version = "0.10.0-elm.1"
edition = "2021"

[dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs", rev = "4f39e5d4046d301d75fb4f16457a996bbda05447", features = ["cli"] }