[package]
name = "uniffi-bindgen"
version = "0.12.0"
edition = "2021"

[dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs/", rev = "fe0d47ab23267415d118e5318feb282cc99ed5d0", features = ["cli"] }