[package]
name = "uniffi-bindgen"
version = "0.10.0-damson.1"
edition = "2021"

[dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs", rev = "2218a19b24e260549d1ef7ce72538d2b3d499a32", features = ["cli"] }