documentation = false

[parse]
clean = true
parse_deps = true
include = ["radix-engine-toolkit"]
extra_bindings = ["radix-engine-toolkit"]

[parse.expand]
all_features = true
crates = ["native-json-interface", "radix-engine-toolkit"]