[package]
name = "radix-engine-toolkit-core"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
hex = { version = "0.4.3", default-features = false }
bech32 = { version = "0.9.0", default-features = false }

serde = { version = "1.0.144", default-features = false, features = ["serde_derive"] }
serde_json = { version = "1.0.85", default-features = false, features = ["std"] }
serde_with = { version = "2.0.0", default-features = false, features = ["hex", "macros"] }

sbor = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "develop-e497a8" }
scrypto = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "develop-e497a8", features = ["serde"] }
scrypto_utils = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "develop-e497a8", package = "utils" }
radix_transaction = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "develop-e497a8", features = ["serde"], package = "transaction" }
radix-engine-constants = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "develop-e497a8" }

[dev-dependencies]
lazy_static = "1.4.0"
serde_json = { version = "1.0.85", default-features = false, features = ["std", "preserve_order"] }

[lib]
crate-type = ["lib"]
