[package]
name = "radix-engine-toolkit-core"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = { version = "0.4.3", default-features = false }
bech32 = { version = "0.9.0", default-features = false }

serde = { version = "1.0.144", default-features = false, features = ["serde_derive"] }
serde_json = { version = "1.0.85", default-features = false, features = ["std"] }
serde_with = { version = "2.0.0", default-features = false, features = ["hex", "macros"] }

# Temporarily commented out. Should revert back as soon as some PRs have been merged
# sbor = { git = "https://github.com/radixdlt/radixdlt-scrypto", branch = "refactor/SCRY-303-NonFungible-Address-Manifest" }
# scrypto = { git = "https://github.com/radixdlt/radixdlt-scrypto", branch = "refactor/SCRY-303-NonFungible-Address-Manifest", features = ["serde"] }
# scrypto_utils = { git = "https://github.com/radixdlt/radixdlt-scrypto", branch = "refactor/SCRY-303-NonFungible-Address-Manifest", package = "utils" }
# radix_transaction = { git = "https://github.com/radixdlt/radixdlt-scrypto", branch = "refactor/SCRY-303-NonFungible-Address-Manifest", features = ["serde"], package = "transaction" }
# radix-engine-constants = { git = "https://github.com/radixdlt/radixdlt-scrypto", branch = "refactor/SCRY-303-NonFungible-Address-Manifest" }

sbor = { path = "/Users/omarabdulla/Desktop/radixdlt-scrypto/sbor" }
scrypto = { path = "/Users/omarabdulla/Desktop/radixdlt-scrypto/scrypto", features = ["serde"] }
scrypto_utils = { path = "/Users/omarabdulla/Desktop/radixdlt-scrypto/utils", package = "utils" }
radix_transaction = { path = "/Users/omarabdulla/Desktop/radixdlt-scrypto/transaction", features = ["serde"], package = "transaction" }
radix-engine-constants = { path = "/Users/omarabdulla/Desktop/radixdlt-scrypto/radix-engine-constants" }

[dev-dependencies]
lazy_static = "1.4.0"

[lib]
crate-type = ["lib"]
