[package]
name = "schema"
version = "0.1.0"
edition = "2021"

[dependencies]
# A fork of a library that allows us to derive a JSON schema for models. This fork adds partial 
# support for serde_with
schemars = { git = "https://github.com/radixdlt/schemars", branch = "feature/partial-serde_with-support" }

# Used to serialize the schema to JSON
serde_json = "1.0.91"

# Importing core to get the models to generate it
core = { path = "../core" }
serde = "1.0.152"
