[bindings.kotlin]
package_name = "com.radixdlt.ret"

[bindings.csharp]
namespace_name = "RadixEngineToolkit"

namespace = "RadixEngineToolkit"

[bindings.go.custom_types.HashableBytes]
type_name = "string"
from_custom = "[]byte({})"
into_custom = "return string({})"
