[package]
name = "uniffi-bindgen"
version = "1.0.3"
edition = "2021"

[dependencies]
uniffi = { git = "https://github.com/mstrug-rdx/uniffi-rs/", rev = "2c6b351cc2ef11c16eff161f43b14f0fab8fd4f3", features = ["cli"] }