[package]
name = "uniffi-bindgen"
version = "1.0.3"
edition = "2021"

[dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs/", rev = "68b14c95a653b8da3a57b8417d1142bd190eac38", features = ["cli"] }