name: Build

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: macos-latest
    continue-on-error: false
    strategy:
      matrix:
        # Update this when we add new interface crates or targets
        crate:
          - name: radix-engine-toolkit-native
            build-target: [aarch64-apple-darwin, x86_64-apple-darwin, aarch64-apple-ios-sim, aarch64-apple-ios, x86_64-apple-ios, x86_64-pc-windows-gnu, x86_64-unknown-linux-gnu]
          - name: radix-engine-toolkit-wasm
            build-target: [wasm32-unknown-unknown]
          - name: radix-engine-toolkit-jni
            build-target: [aarch64-apple-darwin, x86_64-apple-darwin, aarch64-apple-ios-sim, aarch64-apple-ios, x86_64-apple-ios, x86_64-pc-windows-gnu, x86_64-unknown-linux-gnu, aarch64-linux-android, armv7-linux-androideabi, i686-linux-android]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh
          chmod +x rustup.sh
          ./rustup.sh -y
          rustup update
          rustup toolchain install nightly

      # When we require an additional target, do not forget to add it to this list of targets that
      - name: Install Rust Targets
        run: |
          rustup target install ${{ matrix.crate.build-target }}
          rustup +nightly target install ${{ matrix.crate.build-target }}

      - name: Install Build Dependencies
        run: |
          brew tap SergioBenitez/osxct
          brew install llvm
          brew install x86_64-unknown-linux-gnu
          brew install mingw-w64

      # - name: Build ${{ matrix.target }}
      #   continue-on-error: true
      #   run: |
      #     rustup target add ${{ matrix.rust-target }}
      #     rustup +nightly target add ${{ matrix.rust-target }}
      #     rustup component add rust-src --toolchain nightly-x86_64-apple-darwin
      #     cargo install --force cbindgen cross
      #     brew install llvm
      #     export AR="/usr/local/opt/llvm/bin/llvm-ar"
      #     export CC="/usr/local/opt/llvm/bin/clang"
      #     brew install binaryen
      #     ./build.sh radix-engine-toolkit-${{ matrix.target }}

      # - name: Upload ${{ matrix.target }} artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: radix-engine-toolkit-${{ matrix.target }}
      #     path: build/radix-engine-toolkit-${{ matrix.target }}-*
