name: Publish Native Packages

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  publish-csharp-nuget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          path: artifacts
      - name: Extract Artifacts
        working-directory: artifacts
        run: |
          mkdir native
          
          for d in native-json-interface-*.tar.gz; do
            mv ./$d/* ./native/
          done
          
          cd native
          
          for f in *.tar.gz; do 
            fn=`echo "$f" | cut -d'.' -f 1`
            mkdir "$fn"
            tar -xvzf "$f" --directory="$fn";
          done
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@5a3fa01c67e60dba8f95e2878436c7151c4b5f01
        with:
          dotnet-version: 7.0.x
      - name: Configure Version # TODO missing support for stable packages on releases (where VERSION_SUFFIX should not be appended)
        run: |
          GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD | sed 's/\//-/g')
          GIT_COMMIT=$(git log -1 --format=%h )
          CORE_VERSION=$(cat radix-engine-toolkit/Cargo.toml | grep -e '^version' | cut -d'"' -f 2)
          VERSION_SUFFIX=${GIT_BRANCH}-${GIT_COMMIT}
          VERSION=${CORE_VERSION}-${VERSION_SUFFIX}

          sed -i "s/\(<version>\)[^<>]*\(<\/version>\)/\1$VERSION\2/g" interop/csharp/RadixDlt.RadixEngineToolkit.Native.nuspec

          echo "Configured Version: $VERSION"
      - name: NuGet Pack
        working-directory: interop/csharp
        run: nuget pack
      - name: Publish Packages
        working-directory: interop/csharp
        run: dotnet nuget push RadixDlt.RadixEngineToolkit.Native.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_ORG_API_KEY }}
        
          
