name: Release

on:
  push:

jobs:
  setup:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [ native, wasm, jni ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true

      - if: always()
        name: Build ${{ matrix.target }}
        run: |
          rustup target add wasm32-unknown-unknown x86_64-apple-ios aarch64-apple-ios aarch64-apple-ios-sim
          rustup target install wasm32-unknown-unknown
          rustup component add rust-src --toolchain nightly-x86_64-apple-darwin
          cargo install --force cbindgen cross
          whereis clang
          pwd
          ls
          ls /opt/homebrew/opt
#          brew install llvm docker
#          export AR="/opt/homebrew/opt/llvm/bin/llvm-ar"
#          export CC="/opt/homebrew/opt/llvm/bin/clang"
#          ./build.sh radix-engine-toolkit-${{ matrix.target }}
