name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          path: artifacts

      - name: Upload artifact to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: artifacts/radix-engine-toolkit-*/*
          allowUpdates: true
