name: Release

on:
  push:

jobs:
  setup:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true
#
#      - name: Set up cargo cache
#        id: cache-rust
#        uses: actions/cache@v3
#        continue-on-error: false
#        with:
#          path: |
#            ~/.cargo/
#            target/
#          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
#          restore-keys: ${{ runner.os }}-cargo-

      #- if: ${{ steps.cache-rust.outputs.cache-hit != 'true' }}
      - name: Install rust packages
        run: |
          rustup target add wasm32-unknown-unknown x86_64-apple-ios aarch64-apple-ios aarch64-apple-ios-sim
          rustup component add rust-src --toolchain nightly-x86_64-apple-darwin
          cargo install --force cbindgen cross

      - name: Install system packages
        run: |
          brew install llvm docker
          export AR="/opt/homebrew/opt/llvm/bin/llvm-ar"
          export CC="/opt/homebrew/opt/llvm/bin/clang"
          brew install binaryen

      - name: Build
        run: |
          ./build.sh
#
#  build:
#    runs-on: macos-latest
#    needs: [setup]
#
#    strategy:
#      matrix:
#        target: [native, wasm, jni]
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Set up cargo cache
#        uses: actions/cache@v3
#        continue-on-error: false
#        with:
#          path: |
#            ~/.cargo/
#            target/
#          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
#          restore-keys: ${{ runner.os }}-cargo-
#
#      - name: Build ${{ matrix.target }}
#        run: |
#          cd radix-engine-toolkit-${{ matrix.target }}
#          ./build.sh
