name: Release

on:
  push:

jobs:
  setup:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [ native, wasm, jni ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true

      - if: always()
        name: Build ${{ matrix.target }}
        run: |
          brew install llvm docker
          ls /opt/homebrew/opt
#          export AR="/opt/homebrew/opt/llvm/bin/llvm-ar"
#          export CC="/opt/homebrew/opt/llvm/bin/clang"
#          ./build.sh radix-engine-toolkit-${{ matrix.target }}
