name: Test

on:
  pull_request:
    branches:
      - betanet
      - develop
      - main
  push:
    branches:
      - betanet
      - develop
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate: [ radix-engine-toolkit-core, radix-engine-toolkit-native, radix-engine-toolkit-jni, radix-engine-toolkit-wasm]

    steps:
    - uses: actions/checkout@v3
    - name: Install Targets
      run: rustup target install wasm32-unknown-unknown
    - name: Run tests
      run: cargo test --manifest-path ./${{ matrix.crate }}/Cargo.toml --verbose

  generated-requests-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checking Generated Requests
        run: |
          cd docs-examples-generator
          mv request-examples.md old-request-examples.md
          cargo run
          cmp --quiet request-examples.md old-request-examples.md && exit 0 || exit 1