name: Test

on:
  pull_request:
    branches:
      - main
      - develop
      - release/*
  push:
    branches:
      - main
      - develop
      - release/*

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate: [ native-json-library, radix-engine-toolkit ]

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --manifest-path ./${{ matrix.crate }}/Cargo.toml --verbose