# Testing CI - Runs on each PR and Push

name: Test
on:
  pull_request:
  push:
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2023-11-24
        override: true
        components: rustfmt, clippy
    - name: Install cargo nextest
      uses: baptiste0928/cargo-install@v1
      with:
        crate: cargo-nextest
        locked: true
    - name: Install JNA
      run: wget https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar
    - name: Run tests
      run: cargo nextest run
      env:
        # Required env-var to increase the heapsize when using `kotlinc`.
        JAVA_OPTS: "-Xmx8g"
        # Required for Kotlin Uniffi tests
        CLASSPATH: "./jna-5.13.0.jar"
  check-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2023-11-24
        override: true
        components: rustfmt, clippy
    - name: Check formatting
      run: cargo fmt --check
  build-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2023-11-24
        override: true
        profile: minimal
    - name: Cargo Check
      run: cargo check --all