# Testing CI - Runs on each PR and Push

name: Test
on:
  pull_request:
  push:
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2023-11-24
        override: true
        components: rustfmt, clippy
    - name: Run tests
      run: cargo test
      env:
        # Required env-var to increase the heapsize when using `kotlinc`.
        JAVA_OPTS: "-Xmx8g"
  check-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2023-11-24
        override: true
        components: rustfmt, clippy
    - name: Check formatting
      run: cargo fmt --check
  build-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2023-11-24
        override: true
        profile: minimal
    - name: Cargo Check
      run: cargo check